### ISSUE TITLE
Set up testing

### ISSUE THREAD

**Issue by mikevespi** [button-inc/digital_marketplace#8]
(Finish?) setting up testing frameworks

**Comment by wenzowski** [comment]
As worded, this doesn't read like a [thin vertical slice](https://trunkbaseddevelopment.com/observed-habits/#thin-vertical-slices) of functionality despite the fact that I think we're on the same page. For our future selves: how will we know when we're done? We could keep adding testing frameworks and tweaking our setup forever. I recall from our convo this morning we were talking about jest. Is the essence of this to land https://github.com/bcgov/digital_marketplace/pull/195?

I'd suggest that perhaps we could extend https://github.com/button-inc/digital_marketplace/issues/15 to include running scans via the [sonarcloud-github-action](https://github.com/SonarSource/sonarcloud-github-action) instead of the automated runner so we can see the jest suite test coverage? Doing so would enable a future team agreement of "no test coverage regressions".

**Comment by BCerki** [comment]
Installed and configured jest and cypress.
